name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions: write-all

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - uses: nrwl/nx-set-shas@v4

      - run: npx nx format:check
      - run: npx nx affected -t lint test
      - run: git config --global user.email "igor@katsuba.dev"
      - run: git config --global user.name "IKatsuba"
      - run: npx nx release -y --verbose
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
